# Generated by Django 5.1 on 2024-08-15 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', related_query_name='event', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.basemodel')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('overview', models.TextField(verbose_name='overview')),
                ('myevent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas', related_query_name='idea', to='events.event')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas', related_query_name='idea', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('common.basemodel',),
        ),
    ]
