# Generated by Django 5.1 on 2024-08-15 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_organizer_idea'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idea',
            old_name='myevent',
            new_name='my_event',
        ),
    ]
